### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by saesrpg** [NodeBB/nodebb-plugin-poll#101]
Currently getting these warnings, I know they don't affect usage however I thought I would report it.

```
2019-02-06T14:12:57.237Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:5:14
2019-02-06T14:12:57.238Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./settings')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:6:20
2019-02-06T14:12:57.238Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./meta')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:7:16
2019-02-06T14:12:57.239Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:8:16
2019-02-06T14:12:57.239Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./posts')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:9:17
2019-02-06T14:12:57.240Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./topics')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:10:18
2019-02-06T14:12:57.240Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./privileges')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:11:22
2019-02-06T14:12:57.241Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/plugins')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:12:25
2019-02-06T14:12:57.241Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/admin')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:13:24
2019-02-06T14:12:57.241Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/index')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:14:23
2019-02-06T14:12:57.242Z [4999/23748] - warn: [deprecated] requiring core modules with `module.parent.require('../public/src/modules/translator')` is deprecated. Please use `require.main.require("./src/<module_name>")` instead.
    at /var/****/node_modules/nodebb-plugin-poll/lib/nodebb.js:15:22
```

**Comment by ufan0** [comment]
https://community.nodebb.org/topic/13749/when-i-installed-nodebb-plugin-poll-log-display-warning-information

**Comment by pitaj** [comment]
Warnings aren't a bug or a feature request. I believe this has been fixed in the nodebb-plugin-poll repository. If not, you should open an issue there.

**Comment by akhoury** [comment]
this was fixed in this, yet to be merged, PR: https://github.com/NodeBB/nodebb-plugin-poll/pull/102
