### ISSUE TITLE
Errors when using in with 1.12.2

### ISSUE THREAD

**Issue by sharked76** [NodeBB/nodebb-plugin-poll#103]
I am seeing these errors for nodebb-plugin-poll:

`2019-05-16T15:34:04.744Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./database')` is deprecated. Please use `require.main.re                                                      quire("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:5:14
2019-05-16T15:34:04.748Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./settings')` is deprecated. Please use `require.main.re                                                      quire("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:6:20
2019-05-16T15:34:04.751Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./meta')` is deprecated. Please use `require.main.requir                                                      e("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:7:16
2019-05-16T15:34:04.753Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./user')` is deprecated. Please use `require.main.requir                                                      e("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:8:16
2019-05-16T15:34:04.776Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./posts')` is deprecated. Please use `require.main.requi                                                      re("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:9:17
2019-05-16T15:34:04.780Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./topics')` is deprecated. Please use `require.main.requ                                                      ire("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:10:18
2019-05-16T15:34:04.781Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./privileges')` is deprecated. Please use `require.main.                                                      require("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:11:22
2019-05-16T15:34:04.782Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/plugins')` is deprecated. Please use `requir                                                      e.main.require("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:12:25
2019-05-16T15:34:04.785Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/admin')` is deprecated. Please use `require.                                                      main.require("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:13:24
2019-05-16T15:34:04.786Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('./socket.io/index')` is deprecated. Please use `require.                                                      main.require("./src/<module_name>")` instead.
    at /home/bgc/nodebb/node_modules/nodebb-plugin-poll/lib/nodebb.js:14:23
2019-05-16T15:34:04.787Z [4567/1010] - warn: [deprecated] requiring core modules with `module.parent.require('../public/src/modules/translator')` is deprecated. Pleas                                                      e use `require.main.require("./src/<module_name>")` instead.
`

**Comment by pitaj** [comment]
Those are warnings, not errors, but they should be fixed.

**Comment by PatheticMustan** [comment]
Should probably still be updated though...

**Comment by akhoury** [comment]
this was fixed [some time ago](https://github.com/NodeBB/nodebb-plugin-poll/commit/931e18133156630622b45f32a4a47fb58a9ed82c)

**Comment by akhoury** [comment]
`npm publish` when ready @julianlam please
